/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-03-02 12:15:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Thanks for  -->\r\n");
      out.write("<!-- 2014HEW Javaを使った楽しいWEBサイト　IT11A247 中山暁登 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Style-Type\" content=\"text/javascript\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/common.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/items.css\">\r\n");
      out.write("\t<script src=\"./js/jquery-2.1.3.min.js\"></script>\r\n");
      out.write("\t<script src=\"./js/jquery.openwin.js\"></script>\r\n");
      out.write("\t<script src=\"./js/jquery.color.js\"></script>\r\n");
      out.write("\t<script src=\"./js/common.js\"></script>\r\n");
      out.write("\t<script src=\"./js/itemAnimation.js\"></script>\r\n");
      out.write("\t<title>FunRoom - 「一人」を「楽しく」。</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"itemAnimeStart();\">\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<p id=\"men\" class=\"colorChange\">Men</p>\r\n");
      out.write("\t\t\t<p id=\"women\" class=\"colorChange\">Women</p>\r\n");
      out.write("\t\t\t<p id=\"default\" class=\"colorChange\">Default</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t<!-- scrollButton -->\r\n");
      out.write("\t\t\t<img src=\"./images/button.png\" alt=\"scrollButton\" width=\"80\" height=\"80\" id=\"scrollButton\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--**** outside ****-->\r\n");
      out.write("\t\t\t<div id=\"outside\" class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- item images -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/outside_01.png\" alt=\"house\" id=\"outside01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/outside_02.png\" alt=\"cloud\" id=\"outside02\" class=\"cloud\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/outside_02.png\" alt=\"cloud\" id=\"outside03\" class=\"cloud\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/outside_04.png\" alt=\"door\" id=\"outside04\" class=\"cloud\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\" class=\"scrollNext\">キッチンへ</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--**** kitchen ****-->\r\n");
      out.write("\t\t\t<div id=\"kitchen\" class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\t\t\t\t\t<!-- item images -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_01.png\" alt=\"sink\" id=\"kitchen01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_02.png\" alt=\"fridge\" id=\"kitchen02\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_03.png\" alt=\"shelf\" id=\"kitchen03\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_04.png\" alt=\"conro\" id=\"kitchen04\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_05.png\" alt=\"fire\" id=\"kitchen05\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_06.png\" alt=\"fire\" id=\"kitchen06_1\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_06.png\" alt=\"fire\" id=\"kitchen06_2\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_07.png\" alt=\"air\" id=\"kitchen07\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_08.png\" alt=\"fire\" id=\"kitchen08_1\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_08.png\" alt=\"fire\" id=\"kitchen08_2\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_08.png\" alt=\"fire\" id=\"kitchen08_3\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_09.png\" alt=\"fire\" id=\"kitchen09\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_10.png\" alt=\"fire\" id=\"kitchen10\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_11.png\" alt=\"fire\" id=\"kitchen11\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_12.png\" alt=\"fire\" id=\"kitchen12\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_13.png\" alt=\"fire\" id=\"kitchen13\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_14.png\" alt=\"fire\" id=\"kitchen14\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_15.png\" alt=\"fire\" id=\"kitchen15\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- animation images -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime01.png\" alt=\"fireanime\" id=\"kitchen_anime01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime11.png\" alt=\"fire\" id=\"kitchen_anime11\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime12.png\" alt=\"fire\" id=\"kitchen_anime12\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime12.png\" alt=\"fire\" id=\"kitchen_anime13\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime21.png\" alt=\"fire\" id=\"kitchen_anime21\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime22.png\" alt=\"fire\" id=\"kitchen_anime22\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime23.png\" alt=\"fire\" id=\"kitchen_anime23\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime24.png\" alt=\"fire\" id=\"kitchen_anime24\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime31.png\" alt=\"fire\" id=\"kitchen_anime31\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime41.png\" alt=\"fire\" id=\"kitchen_anime41\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime42.png\" alt=\"fire\" id=\"kitchen_anime42\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime43.png\" alt=\"fire\" id=\"kitchen_anime43\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime44.png\" alt=\"fire\" id=\"kitchen_anime44\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- bottum shelf -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime51.png\" alt=\"fire\" id=\"kitchen_anime51\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime52.png\" alt=\"fire\" id=\"kitchen_anime52\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- fridge -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime61.png\" alt=\"fire\" id=\"kitchen_anime61\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime62.png\" alt=\"fire\" id=\"kitchen_anime62\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_anime63.png\" alt=\"fire\" id=\"kitchen_anime63\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- clickArea -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_flagConro.png\" alt=\"fire\" id=\"conroFlag\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_flagJaguchi.png\" alt=\"fire\" id=\"jaguchiFlag\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/kitchen_flagSponge.png\" alt=\"fire\" id=\"spongeFlag\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#kitchen\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/kitchen_flagWashing.png\" alt=\"fire\" id=\"washingFlag\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- effect -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/effect01.png\" alt=\"window\" id=\"washed_effect\" class=\"effect\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#bathroom\" class=\"scrollNext\">風呂場へ</a><br /><br />\r\n");
      out.write("\t\t\t\t\t<a href=\"./questionnaire.jsp\" class=\"openwin\">(^-^)v</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!---**** bathroom ****-->\r\n");
      out.write("\t\t\t<div id=\"bathroom\" class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- item images -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_01.png\" alt=\"bath\" id=\"bathroom01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_02.png\" alt=\"bath\" id=\"bathroom02\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_03.png\" alt=\"bath\" id=\"bathroom03\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_04.png\" alt=\"bath\" id=\"bathroom04\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_05.png\" alt=\"bath\" id=\"bathroom05\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_06.png\" alt=\"bath\" id=\"bathroom06\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_07.png\" alt=\"bath\" id=\"bathroom07\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_08.png\" alt=\"bath\" id=\"bathroom08\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_09.png\" alt=\"bath\" id=\"bathroom09\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- animation images -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_anime01.png\" alt=\"bath\" id=\"bathroom_anime01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_anime02.png\" alt=\"bath\" id=\"bathroom_anime02\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_anime03.png\" alt=\"bath\" id=\"bathroom_anime03\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/bathroom_anime04.png\" alt=\"bath\" id=\"bathroom_anime04\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- showerStop -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#bathroom\" onClick=\"showerStop()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/bathroom_flagShower.png\" alt=\"bath\" id=\"showerFlag\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#living\" class=\"scrollNext\">リビングへ</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--**** living ****-->\r\n");
      out.write("\t\t\t<div id=\"living\" class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- item images -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_01.png\" alt=\"bed\" id=\"living01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_02.png\" alt=\"window\" id=\"living02\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_03.png\" alt=\"window\" id=\"living03\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_04.png\" alt=\"window\" id=\"living04\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_05.png\" alt=\"window\" id=\"living05\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_06.png\" alt=\"window\" id=\"living06\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_07.png\" alt=\"window\" id=\"living07\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- animation images -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- clothes -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime01.png\" alt=\"window\" id=\"living_anime01\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime02.png\" alt=\"window\" id=\"living_anime02\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime03.png\" alt=\"window\" id=\"living_anime03\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime04.png\" alt=\"window\" id=\"living_anime04\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- getClothes -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#living\" onClick=\"getClothes()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/living_flagClothes.png\" alt=\"bath\" id=\"clothesFlag\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- books -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime11.png\" alt=\"window\" id=\"living_anime11\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime12.png\" alt=\"window\" id=\"living_anime12\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/living_anime13.png\" alt=\"window\" id=\"living_anime13\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- arrange books -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#living\" onClick=\"arrangeBooks01()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./images/living_flagBooks.png\" alt=\"bath\" id=\"booksFlag\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- effect -->\r\n");
      out.write("\t\t\t\t\t<img src=\"./images/effect01.png\" alt=\"window\" id=\"books_effect\" class=\"effect\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#entrance\"class=\"scrollNext\">玄関へ</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--**** entrance ****-->\r\n");
      out.write("\t\t\t<div id=\"entrance\" class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\t\t\t\t\t<!-- item images -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#bye\"  class=\"scrollNext\">外へ</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- last -->\r\n");
      out.write("\t\t\t<div id=\"bye\" class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#header\" class=\"scrollTop\">ありがとう！</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
