/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-03-07 00:21:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class score_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Score</title>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Style-Type\" content=\"text/javascript\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/common.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/note.css\">\r\n");
      out.write("\t");

		// 文字化け対策
		request.setCharacterEncoding("utf8");
	
		/////  DB環境の構築 　/////
		
		// ドライバのロード
		Class.forName("com.mysql.jdbc.Driver");
		// コネクションの取得
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost/hew2014", "root", "");
		
		// ステートメントの作成
		Statement smt = null;
		smt = con.createStatement();
		
		// SQL文の作成と実行
		String sql = "SELECT NAME, SCORE, COMMENT FROM SCORE ORDER BY SCORE DESC";
		ResultSet rs = smt.executeQuery(sql);
		
		// 結果の取得と表示
		int n = 1;
		while(rs.next()){
	
      out.write("\r\n");
      out.write("\t<div class=\"info\">\r\n");
      out.write("\t\t<div class=\"rank\">\r\n");
      out.write("\t\t\t<p>");
      out.print( n );
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t<p>");
      out.print( rs.getString("NAME") );
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"score\">\t\r\n");
      out.write("\t\t\t<p>");
      out.print( rs.getString("SCORE") );
      out.write("点</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"comment\">\r\n");
      out.write("\t\t\t<p>");
      out.print( rs.getString("COMMENT") );
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		n++;
		}
		//while終点

		smt.close();
		con.close();
	
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
